apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
  annotations:
    {{- if .Values.n8n.ingress.tls }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
    {{- end }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  {{- if .Values.n8n.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.subdomain }}.{{ .Values.domainName }}
      secretName: n8n-tls
  {{- end }}
  rules:
    - host: {{ .Values.subdomain }}.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n-svc
                port:
                  number: 5678